### ISSUE TITLE
Request: Also show time in minutes

### ISSUE THREAD

**Issue by RollingStar** [aviraccoon/super-hexagon-stats#3]
This is only needed for the big leaderboard pages, and only the first page or so of results too.

https://superhexagonstats.herokuapp.com/#!/leaderboard/Hexagon

If you show the time in minutes (in addition to seconds), you can see who's definitely a cheater and who is maybe just really good at the game. A time of 1159.03 seconds = 19.3172 minutes, which is possible for someone who has 200 hours in the game. But the times that turn out to be more than a day are quite far-fetched.

**Comment by aviraccoon** [comment]
Good idea. I wanted to make a few changes soon anyway (finally), so I'll add it. And deal with cheaters.

**Comment by adrian17** [comment]
Hi there, are you still working on the project? I can see people asking about filtering leaderboards on Steam forums once in a while but they are rarely asking you directly.

**Comment by aviraccoon** [comment]
Closing as I'm archiving this repository.
